// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6lKo-NNthbcp5AOmRX2fGrOvkT9bAIjc',
    appId: '1:229554224855:web:cfb8464137a81b9e17fa92',
    messagingSenderId: '229554224855',
    projectId: 'nooler-rpg',
    authDomain: 'nooler-rpg.firebaseapp.com',
    storageBucket: 'nooler-rpg.firebasestorage.app',
    measurementId: 'G-115X2F4LZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJO8b4cFz8e43t5yx6qg2ngh659URQEo',
    appId: '1:533837749555:android:cd14b98b11e237f02b3246',
    messagingSenderId: '533837749555',
    projectId: 'nooler-clicker-rpg',
    storageBucket: 'nooler-clicker-rpg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqy43tIKicz-MUBK7bZl8IKvuY5dWR7sc',
    appId: '1:229554224855:ios:f22b0a5c40a0e03117fa92',
    messagingSenderId: '229554224855',
    projectId: 'nooler-rpg',
    storageBucket: 'nooler-rpg.firebasestorage.app',
    iosBundleId: 'com.example.ryanClickerRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqy43tIKicz-MUBK7bZl8IKvuY5dWR7sc',
    appId: '1:229554224855:ios:f22b0a5c40a0e03117fa92',
    messagingSenderId: '229554224855',
    projectId: 'nooler-rpg',
    storageBucket: 'nooler-rpg.firebasestorage.app',
    iosBundleId: 'com.example.ryanClickerRpg',
  );
}